/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./resources/**/*.{vue,js,ts,jsx,tsx,blade.php}",
    "./resources/js/design-system/**/*.{vue,js,css,html}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      colors: {
        brand: {
          black: "#000000",
          dark: "#050a1f",
          navy: "#0d1b3d",
          accent: "#1a3c8c",
          desk: "#090d16",
          bg: "#090d16",
          surface: "#0f172a",
          elevated: "#13203a",
          primary: "#F59E0B",
          "primary-hover": "#D97706",
          border: "#1e293b",
          text: "#E8EDF5",
          "text-secondary": "#A8B3C7",
          success: "#10B981",
          danger: "#EF4444",
          warning: "#F59E0B",
        },
        ds: {
          "table-surface": "var(--ds-table-surface, #1F2937)",
          "row-selected": "var(--ds-row-selected, #1E1B4B)",
          "row-hover": "var(--ds-row-hover, #374151)",
          accepted: "var(--color-status-accepted, #10B981)",
          negotiation: "var(--color-status-negotiation, #F59E0B)",
          rejected: "var(--color-status-rejected, #EF4444)",
          review: "var(--color-status-review, #818CF8)",
        },
        background: "var(--color-bg)",
        foreground: "var(--color-text-primary)",
        primary: {
          DEFAULT: "var(--color-primary)",
          foreground: "var(--color-bg)",
          hover: "var(--color-primary-hover)",
        },
        border: "var(--color-border)",
        ring: "var(--color-focus)",
        surface: {
          DEFAULT: "var(--color-surface)",
          elevated: "var(--color-surface-elevated)",
          table: "var(--ds-table-surface, #1F2937)",
        },
        success: "var(--color-success)",
        danger: "var(--color-danger)",
        warning: "var(--color-warning)",
      },
      borderRadius: {
        DEFAULT: "4px",
        none: "0",
        sm: "4px",
        md: "4px",
        lg: "4px",
        xl: "4px",
        "2xl": "4px",
        full: "9999px",
        ds: "4px",
      },
      width: {
        sidebar: "260px",
      },
      spacing: {
        sidebar: "260px",
        "row-compact": "32px",
        "row-comfortable": "48px",
      },
    },
  },
  plugins: [],
}
